apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-ragflow-mysql-node06
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /data/ragflow/mysql
    type: ""
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: ragflow-mysql-target
              operator: In
              values:
                - "true"
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-mysql
  volumeMode: Filesystem
